const translations = {
	Sites: 'سایت‌ها',
	Site: 'سایت',
	Benches: 'بنچ‌ها',
	Bench: 'بنچ',
	Servers: 'سرورها',
	Server: 'سرور',
	Marketplace: 'مارکت‌پلیس',
	Billing: 'صورتحساب',
	Settings: 'تنظیمات',
	Status: 'وضعیت',
	'Seller Panel': 'پنل فروشنده',
	Search: 'جستجو',
	Refresh: 'بروزرسانی',
	'No results': 'نتیجه‌ای یافت نشد',
	'No results found': 'موردی یافت نشد',
	'Load more': 'نمایش بیشتر',
	Options: 'گزینه‌ها',
	Filters: 'فیلترها',
	'Change Team': 'تغییر تیم',
	'Support & Docs': 'پشتیبانی و مستندات',
	Logout: 'خروج',
	'Loading...': 'در حال بارگذاری...',
	Overview: 'نمای کلی',
	Forecast: 'پیش‌بینی',
	Invoices: 'فاکتورها',
	Balances: 'موجودی‌ها',
	'Payment Methods': 'روش‌های پرداخت',
	'Marketplace Payouts': 'تسویه‌های مارکت‌پلیس',
	'UPI Autopay': 'پرداخت خودکار UPI',
	Profile: 'پروفایل',
	Team: 'تیم',
	Roles: 'نقش‌ها',
	Developer: 'توسعه‌دهنده',
	'Partner Admin': 'مدیریت شریک',
	'Ongoing Incidents': 'اختلالات جاری',
	'Incident History': 'تاریخچه اختلالات',
	'Dev Tools': 'ابزار توسعه',
	Partnership: 'همکاری',
	Actions: 'اقدامات',
	New: 'جدید',
	List: 'لیست',
	Dashboard: 'داشبورد',
	Customers: 'مشتریان',
	Certificates: 'گواهینامه‌ها',
	Resources: 'منابع',
	Contributions: 'مشارکت‌ها',
	Audits: 'ممیزی‌ها',
	Leads: 'سرنخ‌ها',
	'Website Details': 'جزئیات وب‌سایت',
	Payout: 'تسویه',
	'Local Payment Setup': 'تنظیم پرداخت محلی',
	'View all': 'مشاهده همه',
	Features: 'ویژگی‌ها',
	'Continue Onboarding': 'ادامه راه‌اندازی',
	'Read more →': 'بیشتر بخوانید ←',
	'Finish onboarding to start using Benches.':
		'برای استفاده از بنچ‌ها ابتدا راه‌اندازی اولیه را کامل کنید.',
	'Finish onboarding to start using Servers.':
		'برای استفاده از سرورها ابتدا راه‌اندازی اولیه را کامل کنید.',
	'With Benches, you get more control. You can choose which apps to add, which apps to update, which region to deploy to and more.':
		'با بنچ‌ها کنترل بیشتری دارید. می‌توانید انتخاب کنید چه اپ‌هایی اضافه یا بروزرسانی شوند و در کدام ریجن دیپلوی شوند.',
	'With Servers on Frappe Cloud, you now get dedicated compute resources for your sites. Servers come in pairs (Application + Database). You can run as many sites and benches as you want. All other features like Private Benches, SSH Access, Database Access work as is with servers.':
		'با سرورها در Frappe Cloud منابع اختصاصی برای سایت‌های خود دارید. سرورها به‌صورت جفت (اپلیکیشن + دیتابیس) ارائه می‌شوند و می‌توانید هر تعداد سایت و بنچ داشته باشید.',
	'Containerised deployments': 'دیپلوی کانتینری',
	'Custom app deployment': 'دیپلوی اپ سفارشی',
	'Access to 150+ marketplace apps': 'دسترسی به بیش از ۱۵۰ اپ مارکت‌پلیس',
	'Multi-environment (e.g. Staging, Production)': 'چند محیطی (مانند Staging و Production)',
	'Server scripts': 'اسکریپت‌های سرور',
	'SSH access': 'دسترسی SSH',
	'Dedicated workers': 'ورکرهای اختصاصی',
	'Unlimited sites & benches (no extra cost)': 'سایت و بنچ نامحدود (بدون هزینه اضافه)',
	'Isolated benches as separate environments': 'بنچ‌های ایزوله به‌عنوان محیط جداگانه',
	'Frappe Product Warranty for any 5 opted-in sites':
		'گارانتی محصول Frappe برای ۵ سایت انتخابی',
	'One-click vertical scaling to higher plans': 'افزایش پلن عمودی با یک کلیک',
	'Alerts for resource consumption': 'هشدار مصرف منابع',
	'Features to install, upgrade, backup, monitor & develop apps':
		'امکانات نصب، بروزرسانی، بکاپ، مانیتور و توسعه اپ',
	'Status Code': 'کد وضعیت',
};

export function tr(text) {
	if (typeof text !== 'string') return text;
	return translations[text] || text;
}
