---
- name: Setup Unified Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: nat_iptables
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: mount
    - role: bench
    - role: docker
    - role: mariadb
    - role: mariadb_memory_allocator
    - role: iptables
